[build]
builder = "nixpacks"
buildCommand = "npm ci --include=dev && npx prisma generate && npm run build"

[deploy]
releaseCommand = "node scripts/release.mjs"
startCommand = "node scripts/start.mjs"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
